version: "3.1"
services:
    php82:
      image: adhocore/phpfpm:8.2
      container_name: worstpractice-dependency-injection-php-fpm
      working_dir: /application
      volumes:
        - .:/application
      stdin_open: true
      tty: true
